/// Arabic names of the 114 surahs, indexed from 1 (index 0 is a placeholder).
///
/// Used by the Mushaf surah banner. Kept local and const so rendering a
/// page never needs a repository or network round-trip.
const List<String> kSurahNamesArabic = <String>[
  '',
  'الفاتحة',
  'البقرة',
  'آل عمران',
  'النساء',
  'المائدة',
  'الأنعام',
  'الأعراف',
  'الأنفال',
  'التوبة',
  'يونس',
  'هود',
  'يوسف',
  'الرعد',
  'ابراهيم',
  'الحجر',
  'النحل',
  'الإسراء',
  'الكهف',
  'مريم',
  'طه',
  'الأنبياء',
  'الحج',
  'المؤمنون',
  'النور',
  'الفرقان',
  'الشعراء',
  'النمل',
  'القصص',
  'العنكبوت',
  'الروم',
  'لقمان',
  'السجدة',
  'الأحزاب',
  'سبأ',
  'فاطر',
  'يس',
  'الصافات',
  'ص',
  'الزمر',
  'غافر',
  'فصلت',
  'الشورى',
  'الزخرف',
  'الدخان',
  'الجاثية',
  'الأحقاف',
  'محمد',
  'الفتح',
  'الحجرات',
  'ق',
  'الذاريات',
  'الطور',
  'النجم',
  'القمر',
  'الرحمن',
  'الواقعة',
  'الحديد',
  'المجادلة',
  'الحشر',
  'الممتحنة',
  'الصف',
  'الجمعة',
  'المنافقون',
  'التغابن',
  'الطلاق',
  'التحريم',
  'الملك',
  'القلم',
  'الحاقة',
  'المعارج',
  'نوح',
  'الجن',
  'المزمل',
  'المدثر',
  'القيامة',
  'الإنسان',
  'المرسلات',
  'النبأ',
  'النازعات',
  'عبس',
  'التكوير',
  'الإنفطار',
  'المطففين',
  'الإنشقاق',
  'البروج',
  'الطارق',
  'الأعلى',
  'الغاشية',
  'الفجر',
  'البلد',
  'الشمس',
  'الليل',
  'الضحى',
  'الشرح',
  'التين',
  'العلق',
  'القدر',
  'البينة',
  'الزلزلة',
  'العاديات',
  'القارعة',
  'التكاثر',
  'العصر',
  'الهمزة',
  'الفيل',
  'قريش',
  'الماعون',
  'الكوثر',
  'الكافرون',
  'النصر',
  'المسد',
  'الإخلاص',
  'الفلق',
  'الناس',
];

/// The Arabic name of [surah], or null if out of range.
String? surahNameArabic(int? surah) {
  if (surah == null || surah < 1 || surah >= kSurahNamesArabic.length) {
    return null;
  }
  return kSurahNamesArabic[surah];
}

/// English transliterated names, indexed from 1 (index 0 is a placeholder).
const List<String> kSurahNamesEnglish = <String>[
  '',
  'Al-Fatihah',
  'Al-Baqarah',
  'Aal-E-Imran',
  'An-Nisa',
  'Al-Maidah',
  'Al-An\'am',
  'Al-A\'raf',
  'Al-Anfal',
  'At-Tawbah',
  'Yunus',
  'Hud',
  'Yusuf',
  'Ar-Ra\'d',
  'Ibrahim',
  'Al-Hijr',
  'An-Nahl',
  'Al-Isra',
  'Al-Kahf',
  'Maryam',
  'Ta-Ha',
  'Al-Anbiya',
  'Al-Hajj',
  'Al-Mu\'minun',
  'An-Nur',
  'Al-Furqan',
  'Ash-Shu\'ara',
  'An-Naml',
  'Al-Qasas',
  'Al-Ankabut',
  'Ar-Rum',
  'Luqman',
  'As-Sajdah',
  'Al-Ahzab',
  'Saba',
  'Fatir',
  'Ya-Sin',
  'As-Saffat',
  'Sad',
  'Az-Zumar',
  'Ghafir',
  'Fussilat',
  'Ash-Shura',
  'Az-Zukhruf',
  'Ad-Dukhan',
  'Al-Jathiyah',
  'Al-Ahqaf',
  'Muhammad',
  'Al-Fath',
  'Al-Hujurat',
  'Qaf',
  'Adh-Dhariyat',
  'At-Tur',
  'An-Najm',
  'Al-Qamar',
  'Ar-Rahman',
  'Al-Waqi\'ah',
  'Al-Hadid',
  'Al-Mujadila',
  'Al-Hashr',
  'Al-Mumtahanah',
  'As-Saff',
  'Al-Jumu\'ah',
  'Al-Munafiqun',
  'At-Taghabun',
  'At-Talaq',
  'At-Tahrim',
  'Al-Mulk',
  'Al-Qalam',
  'Al-Haqqah',
  'Al-Ma\'arij',
  'Nuh',
  'Al-Jinn',
  'Al-Muzzammil',
  'Al-Muddaththir',
  'Al-Qiyamah',
  'Al-Insan',
  'Al-Mursalat',
  'An-Naba',
  'An-Nazi\'at',
  'Abasa',
  'At-Takwir',
  'Al-Infitar',
  'Al-Mutaffifin',
  'Al-Inshiqaq',
  'Al-Buruj',
  'At-Tariq',
  'Al-A\'la',
  'Al-Ghashiyah',
  'Al-Fajr',
  'Al-Balad',
  'Ash-Shams',
  'Al-Layl',
  'Ad-Duha',
  'Ash-Sharh',
  'At-Tin',
  'Al-\'Alaq',
  'Al-Qadr',
  'Al-Bayyinah',
  'Az-Zalzalah',
  'Al-\'Adiyat',
  'Al-Qari\'ah',
  'At-Takathur',
  'Al-\'Asr',
  'Al-Humazah',
  'Al-Fil',
  'Quraysh',
  'Al-Ma\'un',
  'Al-Kawthar',
  'Al-Kafirun',
  'An-Nasr',
  'Al-Masad',
  'Al-Ikhlas',
  'Al-Falaq',
  'An-Nas',
];

/// Ayah count per surah, indexed from 1.
const List<int> kSurahAyahCounts = <int>[
  0,
  7, 286, 200, 176, 120, 165, 206, 75, 129, 109, 123, 111,
  43, 52, 99, 128, 111, 110, 98, 135, 112, 78, 118, 64,
  77, 227, 93, 88, 69, 60, 34, 30, 73, 54, 45, 83,
  182, 88, 75, 85, 54, 53, 89, 59, 37, 35, 38, 29,
  18, 45, 60, 49, 62, 55, 78, 96, 29, 22, 24, 13,
  14, 11, 11, 18, 12, 12, 30, 52, 52, 44, 28, 28,
  20, 56, 40, 31, 50, 40, 46, 42, 29, 19, 36, 25,
  22, 17, 19, 26, 30, 20, 15, 21, 11, 8, 8, 19,
  5, 8, 8, 11, 11, 8, 3, 9, 5, 4, 7, 3,
  6, 3, 5, 4, 5, 6,
];

/// Whether each surah is Meccan, indexed from 1.
const List<bool> kSurahIsMeccan = <bool>[
  false,
  true, false, false, false, false, true, true, false,
  false, true, true, true, false, true, true, true,
  true, true, true, true, true, false, true, false,
  true, true, true, true, true, true, true, true,
  false, true, true, true, true, true, true, true,
  true, true, true, true, true, true, false, false,
  false, true, true, true, true, true, true, true,
  false, false, false, false, false, false, false, false,
  false, false, true, true, true, true, true, true,
  true, true, true, true, true, true, true, true,
  true, true, true, true, true, true, true, true,
  true, true, true, true, true, true, true, true,
  true, false, false, true, true, true, true, true,
  true, true, true, true, true, false, true, true,
  true, true,
];

/// First verse (surah, ayah) of each of the 60 hizbs of the Madinah Mushaf,
/// in order (index 0 = hizb 1). Source: quran.com v4 `verses/by_hizb`.
const List<(int, int)> kHizbStarts = <(int, int)>[
  (1, 1), (2, 75), (2, 142), (2, 203), (2, 253), (3, 15),
  (3, 93), (3, 171), (4, 24), (4, 88), (4, 148), (5, 27),
  (5, 82), (6, 36), (6, 111), (7, 1), (7, 88), (7, 171),
  (8, 41), (9, 34), (9, 93), (10, 26), (11, 6), (11, 84),
  (12, 53), (13, 19), (15, 1), (16, 51), (17, 1), (17, 99),
  (18, 75), (20, 1), (21, 1), (22, 1), (23, 1), (24, 21),
  (25, 21), (26, 111), (27, 56), (28, 51), (29, 46), (31, 22),
  (33, 31), (34, 24), (36, 28), (37, 145), (39, 32), (40, 41),
  (41, 47), (43, 24), (46, 1), (48, 18), (51, 31), (55, 1),
  (58, 1), (62, 1), (67, 1), (72, 1), (78, 1), (87, 1),
];

/// Hizb (1..60) containing [surah]:[ayah].
int hizbFor(int surah, int ayah) {
  var hizb = 1;
  for (var i = 0; i < kHizbStarts.length; i++) {
    final (s, a) = kHizbStarts[i];
    if (surah > s || (surah == s && ayah >= a)) hizb = i + 1;
  }
  return hizb;
}

/// English name for [surah], or null when out of range.
String? surahNameEnglish(int? surah) {
  if (surah == null || surah < 1 || surah >= kSurahNamesEnglish.length) {
    return null;
  }
  return kSurahNamesEnglish[surah];
}
